# Generated by Django 5.2.15 on 2026-06-11 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='服务器ID')),
                ('hostname', models.CharField(max_length=100, verbose_name='主机名')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('ssh_port', models.IntegerField(default=22, verbose_name='SSH端口')),
                ('ssh_user', models.CharField(default='root', max_length=50, verbose_name='SSH用户名')),
                ('ssh_password', models.CharField(max_length=500, verbose_name='SSH密码')),
                ('os_version', models.CharField(blank=True, max_length=200, null=True, verbose_name='操作系统版本')),
                ('cpu_cores', models.IntegerField(blank=True, null=True, verbose_name='CPU核心数')),
                ('memory_total_gb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='内存总容量(GB)')),
                ('disk_total_gb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='磁盘总容量(GB)')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用'), ('maintenance', '维护中')], default='active', max_length=20, verbose_name='服务器状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '服务器信息',
                'verbose_name_plural': '服务器信息',
                'db_table': 'servers',
                'indexes': [models.Index(fields=['ip_address'], name='idx_ip'), models.Index(fields=['status'], name='idx_status')],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='指标ID')),
                ('cpu_usage_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='CPU使用率(%)')),
                ('memory_usage_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='内存使用率(%)')),
                ('collect_time', models.DateTimeField(verbose_name='采集时间')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='server_mgr.server', verbose_name='服务器')),
            ],
            options={
                'verbose_name': '监控指标',
                'verbose_name_plural': '监控指标',
                'db_table': 'metrics',
                'indexes': [models.Index(fields=['server', 'collect_time'], name='idx_metric_server_time')],
                'unique_together': {('server', 'collect_time')},
            },
        ),
        migrations.CreateModel(
            name='BaselineResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='基线结果ID')),
                ('check_item', models.CharField(max_length=100, verbose_name='检查项')),
                ('is_pass', models.BooleanField(verbose_name='是否通过')),
                ('detail', models.TextField(blank=True, verbose_name='详情描述')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='检查时间')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='server_mgr.server', verbose_name='服务器')),
            ],
            options={
                'verbose_name': '基线检查结果',
                'verbose_name_plural': '基线检查结果',
                'db_table': 'baseline_results',
                'indexes': [models.Index(fields=['server', 'checked_at'], name='idx_baseline_server_time')],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='告警ID')),
                ('alert_type', models.CharField(max_length=50, verbose_name='告警类型')),
                ('severity', models.CharField(choices=[('warning', '警告'), ('critical', '严重')], default='warning', max_length=20, verbose_name='告警级别')),
                ('detail', models.TextField(verbose_name='告警详情')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已恢复')),
                ('email_sent', models.BooleanField(default=False, verbose_name='是否已发送邮件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='告警时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='恢复时间')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='server_mgr.server', verbose_name='服务器')),
            ],
            options={
                'verbose_name': '告警记录',
                'verbose_name_plural': '告警记录',
                'db_table': 'alerts',
                'indexes': [models.Index(fields=['is_resolved', 'created_at'], name='idx_unresolved'), models.Index(fields=['server'], name='idx_server')],
            },
        ),
    ]
