# Generated by Django 5.2.15 on 2026-06-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_mgr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='API密钥')),
                ('name', models.CharField(max_length=100, verbose_name='应用名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
            ],
            options={
                'verbose_name': 'API密钥',
                'db_table': 'api_keys',
            },
        ),
    ]
